# Generated by Django 3.0.7 on 2020-06-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], max_length=1)),
                ('age', models.CharField(choices=[('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60-65'), ('65', 'старше 65')], max_length=2)),
                ('bottom_pressure', models.IntegerField()),
                ('top_pressure', models.IntegerField()),
            ],
        ),
    ]
