# Generated by Django 3.0.7 on 2020-06-10 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20200608_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_status', models.CharField(choices=[('problem', 'проблема'), ('normally', 'в пределах нормы')], max_length=10, verbose_name='Оценка показателя')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AddField(
            model_name='arterial',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='monitor.Status', verbose_name='Оценка'),
        ),
    ]
