# Generated by Django 3.0.7 on 2020-06-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20200610_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='arterial',
            name='problem',
            field=models.BooleanField(default=False, verbose_name='Проблема?'),
        ),
    ]
