# Generated by Django 3.0.7 on 2020-06-21 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('monitor', '0006_auto_20200614_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='arterial',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='account.Person', verbose_name='Профиль'),
            preserve_default=False,
        ),
    ]
