# Generated by Django 3.0.7 on 2020-06-21 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('monitor', '0007_arterial_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arterial',
            name='person',
        ),
        migrations.AddField(
            model_name='arterial',
            name='person_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.Person', verbose_name='Профиль'),
        ),
    ]
