# Generated by Django 3.0.7 on 2020-06-22 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0009_auto_20200621_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arterial',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Профиль'),
        ),
    ]
