# Generated by Django 3.0.7 on 2020-06-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_auto_20200622_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arterial',
            name='problem',
        ),
        migrations.AlterField(
            model_name='arterial',
            name='age',
            field=models.CharField(default='45', max_length=3, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='arterial',
            name='bottom_pressure',
            field=models.IntegerField(default='80', verbose_name='Нижнее давление'),
        ),
        migrations.AlterField(
            model_name='arterial',
            name='name',
            field=models.CharField(default='Владимир', max_length=10, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='arterial',
            name='sex',
            field=models.CharField(default='Мужчина', max_length=7, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='arterial',
            name='top_pressure',
            field=models.IntegerField(default='120', verbose_name='Верхнее давление'),
        ),
    ]
