# Generated by Django 3.0.7 on 2020-06-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_auto_20200622_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arterial',
            name='status',
        ),
    ]
