# Generated by Django 3.0.7 on 2020-06-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_auto_20200624_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='arterial',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
