# Generated by Django 3.0.7 on 2020-07-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0020_auto_20200707_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='CP',
            field=models.DecimalField(decimal_places=2, default='0.8', max_digits=4, verbose_name='Цветной показатель'),
        ),
        migrations.AlterField(
            model_name='blood',
            name='HCT',
            field=models.DecimalField(decimal_places=2, default='40', max_digits=5, verbose_name='Гематокрит (в % соотношении)'),
        ),
        migrations.AlterField(
            model_name='blood',
            name='RBC',
            field=models.DecimalField(decimal_places=2, default='4.1', max_digits=4, verbose_name='Эритроциты (× 10х12/л)'),
        ),
    ]
