# Generated by Django 3.0.7 on 2020-07-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0023_auto_20200707_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='CP',
            field=models.DecimalField(decimal_places=2, default='0.9', max_digits=5, verbose_name='Цветной показатель'),
        ),
        migrations.AlterField(
            model_name='blood',
            name='ESR',
            field=models.DecimalField(decimal_places=2, default='2.0', max_digits=5, verbose_name='СОЭ (мм/ч)'),
        ),
        migrations.AlterField(
            model_name='blood',
            name='MPV',
            field=models.DecimalField(decimal_places=2, default='8.0', max_digits=5, verbose_name='Средний объем тромбоцитов (фл или мкм3)'),
        ),
        migrations.AlterField(
            model_name='blood',
            name='RBC',
            field=models.DecimalField(decimal_places=2, default='4.1', max_digits=5, verbose_name='Эритроциты (× 10х12/л)'),
        ),
        migrations.AlterField(
            model_name='blood',
            name='WBC',
            field=models.DecimalField(decimal_places=2, default='4.0', max_digits=5, verbose_name='Лейкоциты (× 10х9/л)'),
        ),
    ]
