# Generated by Django 3.0.7 on 2020-07-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0025_auto_20200707_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood',
            name='problem_CP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blood',
            name='problem_ESR',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blood',
            name='problem_HCT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blood',
            name='problem_HGB',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blood',
            name='problem_MCH',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blood',
            name='problem_MCHC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blood',
            name='problem_MCV',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blood',
            name='problem_MPV',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blood',
            name='problem_PLT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blood',
            name='problem_RBC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blood',
            name='problem_RFV',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blood',
            name='problem_WBC',
            field=models.BooleanField(default=False),
        ),
    ]
