# Generated by Django 3.0.7 on 2020-11-16 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_permission', models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пользователь')], max_length=7, verbose_name='Права пользователя')),
            ],
            options={
                'verbose_name': 'Права сотрудника',
                'verbose_name_plural': 'Права сотрудника',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(choices=[('sub', 'Подчиненный'), ('dom', 'Руководитель')], max_length=7, verbose_name='Статус пользователя')),
                ('status_to_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwork.Permission')),
            ],
            options={
                'verbose_name': 'Статус сотрудника',
                'verbose_name_plural': 'Статус сотрудника',
            },
        ),
    ]
