# Generated by Django 3.0.7 on 2020-11-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departament_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_departament', models.CharField(max_length=30, unique=True, verbose_name='Название подразделения')),
            ],
            options={
                'verbose_name': 'Название подразделения',
                'verbose_name_plural': 'Название подразделения',
            },
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status_to_permission',
            new_name='permission',
        ),
        migrations.CreateModel(
            name='List_dom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_list', models.CharField(max_length=30, verbose_name='Название списка')),
                ('name_departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwork.Departament_name')),
            ],
            options={
                'verbose_name': 'Список вышестоящих подразделений',
                'verbose_name_plural': 'Список вышестоящих подразделений',
            },
        ),
    ]
