# Generated by Django 3.0.7 on 2020-11-16 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0002_auto_20201116_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departament_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_dom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='overwork.List_dom', verbose_name='Список начальствующих подразделений')),
                ('name_departament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='overwork.Departament_name', verbose_name='Название подразделения')),
            ],
        ),
    ]
