# Generated by Django 3.0.7 on 2020-11-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0003_departament_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.SmallIntegerField(verbose_name='Количество часов')),
            ],
            options={
                'verbose_name': 'Часы',
                'verbose_name_plural': 'Часы',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', 'Январь'), ('2', 'Февраль'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], max_length=11, verbose_name='Месяц')),
            ],
            options={
                'verbose_name': 'Месяц',
                'verbose_name_plural': 'Месяца',
            },
        ),
        migrations.CreateModel(
            name='Type_day_off',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=20, unique=True, verbose_name='Тип отгула')),
                ('description_type', models.CharField(blank=True, max_length=100, verbose_name='Описание типа отгула')),
            ],
            options={
                'verbose_name': 'Тип отгула',
                'verbose_name_plural': 'Типы отгулов',
            },
        ),
        migrations.CreateModel(
            name='Type_overwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=20, unique=True, verbose_name='Тип переработки')),
                ('description_type', models.CharField(blank=True, max_length=100, verbose_name='Описание типа переработки')),
            ],
            options={
                'verbose_name': 'Тип переработки',
                'verbose_name_plural': 'Тип переработки',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Года',
            },
        ),
        migrations.AlterModelOptions(
            name='departament_info',
            options={'verbose_name': 'Информация о подразделении', 'verbose_name_plural': 'Информация о подразделениях'},
        ),
        migrations.AlterModelOptions(
            name='departament_name',
            options={'verbose_name': 'Название подразделения', 'verbose_name_plural': 'Название подразделений'},
        ),
        migrations.AlterModelOptions(
            name='list_dom',
            options={'verbose_name': 'Список вышестоящих подразделений', 'verbose_name_plural': 'Список вышестоящих подразделениях'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Права сотрудника', 'verbose_name_plural': 'Права сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус сотрудника', 'verbose_name_plural': 'Статус сотрудников'},
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('1', 'Первая'), ('2', 'Вторая'), ('3', 'Третья'), ('4', 'Четвертая'), ('5', 'Пятая')], max_length=11, verbose_name='Неделя')),
                ('date_start', models.SmallIntegerField(verbose_name='Дата начала недели')),
                ('date_end', models.SmallIntegerField(verbose_name='Дата конца недели')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwork.Month', verbose_name='Неделя')),
            ],
            options={
                'verbose_name': 'Неделя',
                'verbose_name_plural': 'Недели',
            },
        ),
        migrations.CreateModel(
            name='Overwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='Во время праздника или выходного дня?')),
                ('amount_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwork.Amount_hour', verbose_name='Количество часов')),
                ('type_overwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwork.Type_overwork', verbose_name='Тип переработки')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwork.Week', verbose_name='К какой неделе относится?')),
            ],
            options={
                'verbose_name': 'Переработка',
                'verbose_name_plural': 'Переработки',
            },
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwork.Year'),
        ),
        migrations.CreateModel(
            name='Day_off',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vacation', models.BooleanField(default=False, verbose_name='Присоединен к отпуску?')),
                ('amount_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwork.Amount_hour', verbose_name='Количество часов')),
                ('type_overwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwork.Type_day_off', verbose_name='Тип отгула')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwork.Week', verbose_name='К какой неделе относится?')),
            ],
            options={
                'verbose_name': 'Отгул',
                'verbose_name_plural': 'Отгулы',
            },
        ),
    ]
