# Generated by Django 3.0.7 on 2020-11-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0004_auto_20201116_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_off',
            name='date',
            field=models.DateField(default='1.11.1999', verbose_name='Дата отгула'),
        ),
        migrations.AddField(
            model_name='overwork',
            name='date',
            field=models.DateField(default='1.11.1999', verbose_name='Дата переработки'),
        ),
    ]
