# Generated by Django 3.0.7 on 2020-11-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0006_auto_20201116_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_off',
            name='date',
            field=models.DateField(verbose_name='Дата отгула'),
        ),
        migrations.AlterField(
            model_name='overwork',
            name='date',
            field=models.DateField(verbose_name='Дата переработки'),
        ),
    ]
