# Generated by Django 3.0.7 on 2020-11-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0007_auto_20201116_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_off',
            name='date',
        ),
        migrations.RemoveField(
            model_name='overwork',
            name='date',
        ),
    ]
