# Generated by Django 3.0.7 on 2020-11-16 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('overwork', '0010_account_week_work_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account_week_work_time',
            options={'verbose_name': 'Сумма переработки и отгулов за неделю', 'verbose_name_plural': 'Сумма переработки и отгулов за неделю'},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('account_week_work_time', models.ManyToManyField(to='overwork.Account_week_work_time', verbose_name='Учет времени за неделю')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwork.Departament_name', verbose_name='Название подразделения')),
                ('profile', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwork.Status', verbose_name='Статус сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
