# Generated by Django 3.0.7 on 2020-11-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0013_auto_20201117_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
