# Generated by Django 3.0.7 on 2020-11-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0015_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='date_end',
            field=models.SmallIntegerField(max_length=2, verbose_name='Дата конца недели'),
        ),
        migrations.AlterField(
            model_name='week',
            name='date_start',
            field=models.SmallIntegerField(max_length=2, verbose_name='Дата начала недели'),
        ),
        migrations.AlterField(
            model_name='week',
            name='week',
            field=models.CharField(choices=[('Первая', 'Первая'), ('Вторая', 'Вторая'), ('Третья', 'Третья'), ('Четвертая', 'Четвертая'), ('Пятая', 'Пятая')], max_length=11, verbose_name='Неделя'),
        ),
    ]
