# Generated by Django 3.0.7 on 2020-11-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0016_auto_20201117_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='permission',
        ),
        migrations.AddField(
            model_name='permission',
            name='descripton_permission',
            field=models.CharField(blank=True, max_length=100, verbose_name='Описание прав'),
        ),
        migrations.AddField(
            model_name='profile',
            name='permission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='overwork.Permission', verbose_name='Права сотрудника'),
        ),
        migrations.AddField(
            model_name='status',
            name='descripton_status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Описание прав'),
        ),
        migrations.AlterField(
            model_name='week',
            name='date_end',
            field=models.SmallIntegerField(verbose_name='Дата конца недели'),
        ),
        migrations.AlterField(
            model_name='week',
            name='date_start',
            field=models.SmallIntegerField(verbose_name='Дата начала недели'),
        ),
        migrations.AlterField(
            model_name='week',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwork.Month', verbose_name='Год и месяц'),
        ),
    ]
