# Generated by Django 3.0.7 on 2020-11-17 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0017_auto_20201117_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_departament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='overwork.Departament_name', verbose_name='Название подразделения')),
            ],
            options={
                'verbose_name': 'Информация о подразделении',
                'verbose_name_plural': 'Информация о подразделениях',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.SmallIntegerField(verbose_name='Ранг подразделения')),
            ],
            options={
                'verbose_name': 'Ранг подразделения',
                'verbose_name_plural': 'Ранги подразделений',
            },
        ),
        migrations.RemoveField(
            model_name='list_dom',
            name='name_departament',
        ),
        migrations.DeleteModel(
            name='Departament_info',
        ),
        migrations.DeleteModel(
            name='List_dom',
        ),
        migrations.AddField(
            model_name='departament',
            name='rank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='overwork.Rank', verbose_name='Ранг подразделения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwork.Departament', verbose_name='Подразделение'),
        ),
    ]
