# Generated by Django 3.0.7 on 2020-11-17 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0018_auto_20201117_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overwork.Rank', verbose_name='Ранг подразделения'),
        ),
    ]
