# Generated by Django 3.0.7 on 2020-11-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0022_auto_20201117_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(max_length=15, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявки',
            },
        ),
        migrations.AddField(
            model_name='day_off',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Во время праздника или выходного дня?'),
        ),
        migrations.AddField(
            model_name='overwork',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Во время праздника или выходного дня?'),
        ),
    ]
