# Generated by Django 3.0.7 on 2020-11-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0024_auto_20201117_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_off',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Во время праздника или выходного дня?'),
        ),
        migrations.AddField(
            model_name='overwork',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Во время праздника или выходного дня?'),
        ),
        migrations.AlterField(
            model_name='status_order',
            name='name_status',
            field=models.CharField(choices=[('Не проверена', 'Не проверена'), ('Отклонена', 'Отклонена'), ('Принята', 'Принята')], default=0, max_length=15, verbose_name='Статус заявки'),
        ),
    ]
