# Generated by Django 3.0.7 on 2020-11-17 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0027_overwork_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overwork',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Во время праздника или выходного дня?'),
        ),
    ]
