# Generated by Django 3.0.7 on 2020-11-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0029_remove_overwork_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_off',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Во время праздника или выходного дня?'),
        ),
        migrations.AddField(
            model_name='overwork',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Во время праздника или выходного дня?'),
        ),
        migrations.AlterField(
            model_name='day_off',
            name='date',
            field=models.DateField(blank=True, default='1999-11-1', verbose_name='Дата отгула'),
        ),
        migrations.AlterField(
            model_name='day_off',
            name='is_vacation',
            field=models.BooleanField(blank=True, default=False, verbose_name='Присоединен к отпуску?'),
        ),
        migrations.AlterField(
            model_name='overwork',
            name='date',
            field=models.DateField(blank=True, default='1999-11-1', verbose_name='Дата переработки'),
        ),
        migrations.AlterField(
            model_name='overwork',
            name='is_holiday',
            field=models.BooleanField(blank=True, default=False, verbose_name='Во время праздника или выходного дня?'),
        ),
    ]
