# Generated by Django 3.0.7 on 2020-11-17 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0030_auto_20201117_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_off',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Проверена?'),
        ),
        migrations.AlterField(
            model_name='overwork',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Проверена?'),
        ),
    ]
