# Generated by Django 3.0.7 on 2020-11-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0032_auto_20201117_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_off',
            name='is_True',
            field=models.BooleanField(default=False, verbose_name='Заявка верна?'),
        ),
        migrations.AddField(
            model_name='overwork',
            name='is_True',
            field=models.BooleanField(default=False, verbose_name='Заявка верна?'),
        ),
        migrations.AlterField(
            model_name='day_off',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Проверена?'),
        ),
        migrations.AlterField(
            model_name='overwork',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Проверена?'),
        ),
    ]
