# Generated by Django 3.0.7 on 2020-11-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0033_auto_20201117_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status_order',
        ),
    ]
