# Generated by Django 3.0.7 on 2020-11-18 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0034_delete_status_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_off',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='overwork.Profile', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='day_off',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='overwork.Week', verbose_name='К какой неделе относится?'),
        ),
        migrations.AddField(
            model_name='overwork',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='overwork.Profile', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='overwork',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='overwork.Week', verbose_name='К какой неделе относится?'),
        ),
        migrations.DeleteModel(
            name='Account_week_work_time',
        ),
    ]
