# Generated by Django 3.0.7 on 2020-11-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overwork', '0037_auto_20201118_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day_off',
            old_name='type_overwork',
            new_name='type_day_off',
        ),
    ]
